# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hlibine <hlibine@student.42lausanne.ch>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/03 16:51:54 by hlibine           #+#    #+#              #
#    Updated: 2025/05/28 14:49:15 by hlibine          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Genral values
NAME		= webserv

CC			= c++
FLAGS		= -Wall -Wextra -Werror -std=c++98

RM			= rm -rf

OBJDIR		= .obj
SRCSDIR		= srcs
INCLDIR		= incl

# Colors
GREEN		= \033[0;32m
ORANGE		= \033[38;5;208m
LBLUE		= \033[0;36m
RESET		= \033[0m
RESETNL		= \033[0m\n

# File
CPP 		= main
SUPP		= 

FILES		= $(addprefix $(SRCSDIR)/, $(CPP)) $(addprefix $(SRCSDIR)/, $(SUPP))

SRCS		= $(FILES:=.cpp)
OBJS		= $(addprefix $(OBJDIR)/, $(notdir $(FILES:=.o)))
HEADER		= $(addprefix $(INCLDIR)/, $(SUPP:=.hpp))

# Rules
all: $(NAME)

$(NAME): $(SRCS) $(HEADER) $(OBJS)
	@printf "$(ORANGE)Compiling $(NAME)$(RESET)"
	@ $(CC) $(OBJS) -o $(NAME)
	@printf "\r\033[K"
	@printf "$(GREEN)$(NAME) compiled$(RESETNL)"

$(OBJDIR)/%.o: $(SRCSDIR)/%.cpp $(HEADER)
	@mkdir -p $(OBJDIR)
	@printf "$(ORANGE)Compiling $@...$(RESET)"
	@$(CC) $(FLAGS) -c $< -o $@
	@printf "\r\033[K"
	@printf "$(GREEN)$@ compiled!$(RESETNL)"

clean:
	@printf "$(ORANGE)Cleaning up...$(RESET)"
	@$(RM) $(OBJDIR) $(OBJS)
	@printf "\r\033[K"
	@printf "$(GREEN)Clean up successful$(RESETNL)"

s_clean:
	@$(RM) $(NAME) $(OBJDIR) $(OBJS)

fclean: s_clean
	@printf "$(ORANGE)Full clean up...$(RESET)"
	@$(RM) $(NAME)
	@printf "\r\033[K"
	@printf "$(GREEN)Full clean up successful$(RESETNL)"

clear: clean

fclear: fclean

re: fclean all

help:
	@printf "$(LBLUE)make$(RESET) : complies the project.\n"
	@printf "$(LBLUE)make all$(RESET) : complies the project.\n"
	@printf "$(LBLUE)make re$(RESET) : recompiles the project.\n"
	@printf "$(LBLUE)make clean$(RESET) : removes the object files.\n"
	@printf "$(LBLUE)make fclean$(RESET) : removes all files generated by this Makefile.\n"

.PHONY: all clean fclean clear fclear re help
